let x;
let y;
const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
console.log(arr);
x = arr.slice(2, 4);
console.log("slice(2, 4): ", x);
console.log(arr);
y = arr.splice(2, 5);
console.log("poslije splice splice(2, 5): ", y);
console.log(arr);